spring:
  datasource:
    url: jdbc:mysql://localhost:3306/allol?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Tkdlzlr$12*
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE